const http=require('http');const fs=require('fs');const path=require('path');const{URL}=require('url');
const PORT=Number(process.env.PORT)||10000;
const COMBINED_API_URL=(process.env.COMBINED_API_URL||'https://analizator-cen-ofertowych-v05-combined-m9as.onrender.com/api/live/combined').replace(/\/$/,'');
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>100000){reject(new Error('Request too large'));req.destroy();}});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(new Error('Nieprawidłowy JSON'))}});req.on('error',reject);});}
function mapPayload(x){return{location:x.location||'Olsztyn',area:Number(x.area||62),tolerance:Number(x.tolerance??10),radius:Number(x.radius||0),propertyType:x.propertyType||'mieszkanie'};}
async function callCombined(payload){const q=new URL(COMBINED_API_URL);for(const[k,v]of Object.entries(mapPayload(payload)))q.searchParams.set(k,String(v));const r=await fetch(q);const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`Combined API zwrócił nie-JSON (HTTP ${r.status})`)}if(!r.ok)throw new Error(data.error||`Combined API HTTP ${r.status}`);return data;}
function serveTester(res){const html='<!doctype html><meta charset="utf-8"><title>N-O diagnostic</title><style>body{font:16px Arial;max-width:900px;margin:40px auto;padding:20px}button{font-size:18px;padding:12px 20px}pre{white-space:pre-wrap;background:#f4f4f4;padding:15px;border-radius:8px}</style><h1>Diagnostyka Nieruchomości-online</h1><p>Olsztyn · mieszkanie · <b>60–62 m²</b> · promień 0 km</p><p>Test kontrolny odcięcia ofert archiwalnych.</p><button onclick="run()">URUCHOM TEST MIESZKAŃ N-O</button><pre id="out">Gotowe.</pre><script>async function run(){const o=document.getElementById('out');o.textContent='Uruchamiam…';try{const r=await fetch('/api/diagnostic-no?location=Olsztyn&area=61&tolerance=1.6393442623&radius=0&propertyType=mieszkanie',{cache:'no-store'});const t=await r.text();o.textContent='HTTP '+r.status+'\n\n'+t}catch(e){o.textContent='BŁĄD: '+e.message}}</script>' ;res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(html);}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS')return send(res,204,{});const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(u.pathname==='/health')return send(res,200,{ok:true,service:'analizator-cen-ofertowych-compat',combinedApi:COMBINED_API_URL});if(u.pathname==='/test-radius.html'||u.pathname==='/test-radius'||u.pathname==='/diagnostic-no.html')return serveTester(res);if(u.pathname==='/api/diagnostic-no'&&(req.method==='GET'||req.method==='HEAD')){const payload={location:u.searchParams.get('location')||'Olsztyn',area:Number(u.searchParams.get('area')||100),tolerance:Number(u.searchParams.get('tolerance')||50),radius:Number(u.searchParams.get('radius')||0),propertyType:u.searchParams.get('propertyType')||'Nieruchomość komercyjna'};console.log('NO_DIAGNOSTIC_REQUEST',JSON.stringify(payload));const data=await callCombined(payload);console.log('NO_DIAGNOSTIC_RESULT',JSON.stringify({sources:data.sources,beforeCrossDedup:data.beforeCrossDedup,unique:data.unique,duplicatesRemoved:data.duplicatesRemoved,offersCount:Array.isArray(data.offers)?data.offers.length:null}));return send(res,200,data)}if(u.pathname==='/'){return send(res,200,{ok:true,service:'Analizator Cen Ofertowych',status:'backend-online',message:'Backend działa. Użyj /diagnostic-no.html.'})}if(u.pathname==='/api/search-offers'&&(req.method==='POST'||req.method==='GET')){const payload=req.method==='POST'?await body(req):Object.fromEntries(u.searchParams.entries());const data=await callCombined(payload);return send(res,200,{...data,compatibility:{endpoint:'/api/search-offers',forwardedTo:'/api/live/combined'}});}return send(res,404,{error:'Nie znaleziono endpointu.'});}catch(e){console.error('COMPAT_ERROR',e.stack||e.message||e);return send(res,502,{error:e.message||'Błąd bramy API'})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`COMPAT_GATEWAY listening on ${PORT}; combined=${COMBINED_API_URL}`));