const https=require('https');const{URL}=require('url');const PORTAL='Otodom';const BASE='https://www.otodom.pl';
function httpGet(url,timeoutMs=20000){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','Accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','Accept-Language':'pl-PL,pl;q=0.9,en;q=0.8'}},res=>{let body='';res.setEncoding('utf8');res.on('data',c=>body+=c);res.on('end',()=>resolve({status:res.statusCode||0,body}));});req.setTimeout(timeoutMs,()=>req.destroy(new Error('Timeout Otodom')));req.on('error',reject);});}
function slugify(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/ł/g,'l').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
function buildUrl(location,minArea,maxArea,page=1,radius=0,propertyType='mieszkanie'){const city=slugify(location);const type=String(propertyType||'mieszkanie').toLowerCase().includes('dom')?'dom':'mieszkanie';const u=new URL(`${BASE}/pl/wyniki/sprzedaz/${type}/warminsko--mazurskie/${city}/${city}/${city}`);u.searchParams.set('areaMin',String(Math.floor(minArea)));u.searchParams.set('areaMax',String(Math.ceil(maxArea)));const r=Number(radius)||0;if([5,10,15,25,50,75].includes(r))u.searchParams.set('distanceRadius',String(r));if(page>1)u.searchParams.set('page',String(page));return u.href;}
function cleanText(v){return String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&quot;/g,'\"').replace(/&#39;|&#x27;/g,"'").replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();}
function decode(v){return String(v||'').replace(/\\u002F/g,'/').replace(/\\u0026/g,'&').replace(/\\u003D/g,'=').replace(/\\u002D/g,'-').replace(/\\u003A/g,':').replace(/\\u0022/g,'\"');}
function numberFrom(v){if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v!=='string')return NaN;let s=v.trim().replace(/\u00a0/g,' ').replace(/\s/g,'').replace(/zł|PLN/gi,'');if(/^\d{1,3}(?:\.\d{3})+(?:,\d+)?$/.test(s))return Number(s.replace(/\./g,'').replace(',','.'));if(/^\d+(?:,\d+)?$/.test(s))return Number(s.replace(',','.'));return NaN;}
function absoluteUrl(v,b){try{return new URL(decode(v),b).href}catch{return'';}}
function normalizePrice(n,area){if(!Number.isFinite(n)||!Number.isFinite(area))return NaN;let p=n;while(p>3000000)p/=10;const ppm=p/area;if(ppm<3000||ppm>30000)return NaN;return Math.round(p*100)/100;}
function extractPrice(text,area){const candidates=[];const re=/(\d{1,3}(?:[ .]\d{3})+(?:,\d{1,2})?|\d{4,8})(?:\,\d{1,2})?\s*(?:zł|PLN)/gi;for(const m of text.matchAll(re)){const after=text.slice(m.index+m[0].length,m.index+m[0].length+12);if(/^\s*\/\s*m[²2]/i.test(after))continue;const n=numberFrom(m[1]);const p=normalizePrice(n,area);if(Number.isFinite(p))candidates.push(p);}return candidates.length?candidates[candidates.length-1]:NaN;}
function extractArea(text){for(const m of text.matchAll(/(\d+(?:[.,]\d+)?)\s*m[²2]/gi)){const n=numberFrom(m[1]);if(Number.isFinite(n)&&n>=10&&n<=1000)return n;}return NaN;}
function extractTitle(block){const patterns=[/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i,/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i,/<a[^>]+href=["']\/pl\/oferta\/[^"']+["'][^>]*>([\s\S]*?)<\/a>/i];for(const r of patterns){const m=block.match(r);if(m){const t=cleanText(m[1]);if(t&&t.length>=8&&!/Info\.tsx|css-|grid-template|Liczba pokoi/i.test(t))return t;}}return'';}
function parseOffers(html,sourceUrl,propertyType='mieszkanie'){const offers=[],seen=new Set();const matches=[...html.matchAll(/href=["'](\/pl\/oferta\/[^"'#?]+)["']/gi)];for(let i=0;i<matches.length;i++){const m=matches[i],url=absoluteUrl(m[1],sourceUrl);if(!url||seen.has(url))continue;const start=m.index,end=i+1<matches.length?matches[i+1].index:Math.min(html.length,start+18000),block=html.slice(Math.max(0,start-4000),end),text=cleanText(block),area=extractArea(text),price=extractPrice(text,area),title=extractTitle(block);if(Number.isFinite(price)&&Number.isFinite(area)){seen.add(url);offers.push({portal:PORTAL,type:String(propertyType||'mieszkanie').toLowerCase().includes('dom')?'Dom':'Mieszkanie',locality:'',street:'',location:'',url,title,price,area,priceM2:price/area});}}return offers;}
async function searchOtodom({location='Olsztyn',areaTarget=62,tolerance=10,radius=0,maxPages=20,propertyType='mieszkanie'}={}){const minArea=areaTarget*(1-tolerance/100),maxArea=areaTarget*(1+tolerance/100),pages=[],all=[];let totalHtmlLength=0,httpStatus=0,fetched=false,error='',recognized=0,emptyPages=0,previousSignature='';const requestedRadius=Number(radius)||0;const supportedRadius=[0,5,10,15,25,50,75].includes(requestedRadius)?requestedRadius:0;for(let page=1;page<=maxPages;page++){const url=buildUrl(location,minArea,maxArea,page,supportedRadius,propertyType);try{const r=await httpGet(url);httpStatus=r.status;totalHtmlLength+=r.body.length;fetched=fetched||r.status>=200&&r.status<400;const offers=parseOffers(r.body,url,propertyType);recognized+=offers.length;const filtered=offers.filter(o=>o.area>=minArea&&o.area<=maxArea&&Number.isFinite(o.price)&&o.url);all.push(...filtered);const signature=offers.map(o=>o.url).join('|');pages.push({page,url,httpStatus:r.status,htmlLength:r.body.length,recognized:offers.length,filtered:filtered.length});if(offers.length===0)emptyPages++;else emptyPages=0;if(page>1&&signature===previousSignature)break;previousSignature=signature;if(emptyPages>=1)break;}catch(e){error=String(e?.message||e);pages.push({page,url,httpStatus,htmlLength:0,recognized:0,filtered:0,error});break;}}const unique=[],seen=new Set();for(const o of all){const k=o.url.toLowerCase().replace(/\/$/,'');if(seen.has(k))continue;seen.add(k);unique.push(o);}return{portal:PORTAL,httpStatus,fetched,htmlLength:totalHtmlLength,recognized,complete:unique.length,filtered:unique.length,requestedRadius,appliedRadius:supportedRadius,radiusSupported:true,radiusStrategy:supportedRadius>0?'Otodom distanceRadius':'Otodom search without radius',pagesFetched:pages.length,portalAreaRange:{min:minArea,max:maxArea},pages,offers:unique,...(error?{error}:{})};}
module.exports={searchOtodom,buildUrl};