const { URL } = require("url");
const PORTAL = "Nieruchomości-online";
const AVAILABLE_RADII = [0,5,10,15,20,25,50];
function asNumber(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;const s=String(v).replace(/\s/g,'').replace(',','.').replace(/[^0-9.\-]/g,'');const n=Number(s);return Number.isFinite(n)?n:null;}
function absUrl(href,base){if(!href)return '';try{return new URL(href,base).href}catch{return '';}}
function makeOffer(source,locality,street,price,area,url,type='Lokal mieszkalny',title=''){locality=String(locality||'').trim();street=String(street||'').trim();return{source,type,locality,street,location:locality?(street?`${locality}, ${street}`:locality):'',url:String(url||''),price,area,priceM2:price!=null&&area!=null&&area>0?price/area:null,title};}
function walkOffers(x,out){if(Array.isArray(x))return x.forEach(v=>walkOffers(v,out));if(!x||typeof x!=='object')return;const t=x['@type'];if(t==='Offer'||(Array.isArray(t)&&t.includes('Offer')))out.push(x);Object.values(x).forEach(v=>walkOffers(v,out));}
function parseJsonLd(html){const offers=[];const re=/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{walkOffers(JSON.parse(m[1].trim()),offers)}catch(_){}}return{offers};}
function parseNieruchomosciOnline(html,base){const parsed=parseJsonLd(html),rows=[];for(const o of parsed.offers){const item=o.itemOffered||{},addr=item.address||{},fs=item.floorSize||{};const price=asNumber(o.price),area=asNumber(fs.value),url=absUrl(o.url,base);rows.push(makeOffer(PORTAL,addr.addressLocality||'',addr.streetAddress||'',price,area,url,'Lokal mieszkalny',o.name||''));}return{source:PORTAL,recognized:parsed.offers.length,offers:rows};}
async function fetchHtml(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'pl-PL,pl;q=0.9,en;q=0.8'}});return{status:response.status,ok:response.ok,finalUrl:response.url,html:await response.text()};}finally{clearTimeout(timer);}}
function slugLocation(location='Olsztyn'){return String(location).trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ł/g,'l').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function resolveRadius(radius){const requested=Math.max(0,Number(radius)||0);return AVAILABLE_RADII.find(x=>x>=requested)??AVAILABLE_RADII[AVAILABLE_RADII.length-1];}
function escapeRegExp(v){return String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function findPortalLocationId(html,location){const name=String(location||'').trim();if(!name)return '';const re=new RegExp(`${escapeRegExp(name)}\\s*:\\s*([0-9]{3,})`,'i');const m=String(html||'').match(re);return m?m[1]:'';}
async function searchNieruchomosciOnline({location='Olsztyn',path,radius=0}={}){const slug=slugLocation(location),requestedRadius=Math.max(0,Number(radius)||0);let url,appliedRadius=0,locationId='';if(path){url=new URL(`https://${slug}.nieruchomosci-online.pl${path}`);}else if(requestedRadius>0){const baseUrl=`https://${slug}.nieruchomosci-online.pl/mieszkania/sprzedaz/`;const base=await fetchHtml(baseUrl);locationId=findPortalLocationId(base.html,location);if(locationId){appliedRadius=resolveRadius(requestedRadius);url=new URL(`https://www.nieruchomosci-online.pl/szukaj.html?3,mieszkanie,sprzedaz,,${location}:${locationId},,,${appliedRadius}&q=`);}else{url=new URL(baseUrl);appliedRadius=0;}}else{url=new URL(`https://${slug}.nieruchomosci-online.pl/mieszkania/sprzedaz/`);}const result=await fetchHtml(url.href),parsed=parseNieruchomosciOnline(result.html,result.finalUrl||url.href);return{portal:PORTAL,requestedLocation:location,url:result.finalUrl||url.href,httpStatus:result.status,fetched:result.ok,htmlLength:result.html.length,recognized:parsed.recognized,complete:parsed.offers.filter(o=>o.locality&&o.price!=null&&o.area!=null&&o.url).length,offers:parsed.offers,requestedRadius,appliedRadius,radiusSupported:requestedRadius===0||appliedRadius>0,locationId};}
module.exports={PORTAL,parseNieruchomosciOnline,fetchHtml,searchNieruchomosciOnline};