const https=require('https');const{URL}=require('url');const PORTAL='Otodom';const BASE='https://www.otodom.pl';
function httpGet(url,timeoutMs=20000){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','Accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','Accept-Language':'pl-PL,pl;q=0.9,en;q=0.8'}},res=>{let body='';res.setEncoding('utf8');res.on('data',c=>body+=c);res.on('end',()=>resolve({status:res.statusCode||0,body}));});req.setTimeout(timeoutMs,()=>req.destroy(new Error('Timeout Otodom')));req.on('error',reject);});}
function slugify(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/ł/g,'l').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
function buildUrl(location,minArea,maxArea,page=1,radius=0,propertyType='mieszkanie'){const city=slugify(location);const pt=String(propertyType||'mieszkanie').toLowerCase();let type='mieszkanie';if(pt.includes('dom'))type='dom';else if(pt.includes('dział')||pt.includes('dzial'))type='dzialka';else if(pt.includes('hale')||pt.includes('magaz'))type='haleimagazyny';else if(pt.includes('lokal')||pt.includes('komerc'))type='lokal';const u=new URL(`${BASE}/pl/wyniki/sprzedaz/${type}/warminsko--mazurskie/${city}/${city}/${city}`);u.searchParams.set('areaMin',String(Math.max(0,Math.floor(minArea))));u.searchParams.set('areaMax',String(Math.max(0,Math.ceil(maxArea))));const r=Number(radius)||0;if([5,10,15,25,50,75].includes(r))u.searchParams.set('distanceRadius',String(r));if(page>1)u.searchParams.set('page',String(page));return u.href;}
function cleanText(v){return String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&quot;/g,'\"').replace(/&#39;|&#x27;/g,"'").replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();}
function decode(v){return String(v||'').replace(/\\u002F/g,'/').replace(/\\u0026/g,'&').replace(/\\u003D/g,'=').replace(/\\u002D/g,'-').replace(/\\u003A/g,':').replace(/\\u0022/g,'\"');}
function numberFrom(v){if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v!=='string')return NaN;let s=v.trim().replace(/\u00a0/g,' ').replace(/\s/g,'').replace(/zł|PLN/gi,'');if(/^\d{1,3}(?:\.\d{3})+(?:,\d+)?$/.test(s))return Number(s.replace(/\./g,'').replace(',','.'));if(/^\d+(?:,\d+)?$/.test(s))return Number(s.replace(',','.'));return NaN;}
function absoluteUrl(v,b){try{return new URL(decode(v),b).href}catch{return'';}}
function normalizePrice(n,area){if(!Number.isFinite(n)||!Number.isFinite(area))return NaN;let p=n;while(p>3000000)p/=10;const ppm=p/area;if(ppm<30||ppm>30000)return NaN;return Math.round(p*100)/100;}
function extractAreaCandidates(text){const out=[];const re=/(\d+(?:[.,]\d+)?)\s*m[²2]/gi;for(const m of text.matchAll(re)){const n=numberFrom(m[1]);if(Number.isFinite(n)&&n>=10&&n<=100000)out.push({value:n,index:m.index||0});}return out;}
function extractPriceCandidates(text,area){const out=[];const re=/(\d{1,3}(?:[ .]\d{3})+(?:,\d{1,2})?|\d{4,8})(?:\,\d{1,2})?\s*(?:zł|PLN)/gi;for(const m of text.matchAll(re)){const after=text.slice((m.index||0)+m[0].length,(m.index||0)+m[0].length+12);if(/^\s*\/\s*m[²2]/i.test(after))continue;const n=numberFrom(m[1]);const p=normalizePrice(n,area);if(Number.isFinite(p))out.push({value:p,index:m.index||0});}return out;}
function extractArea(text){const a=extractAreaCandidates(text);return a.length?a[0].value:NaN;}
function extractPrice(text,area){const p=extractPriceCandidates(text,area);return p.length?p[p.length-1].value:NaN;}
function extractTitle(block){const patterns=[/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i,/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i,/<a[^>]+href=["'](?:https?:\/\/www\.otodom\.pl)?\/pl\/oferta\/[^"']+["'][^>]*>([\s\S]*?)<\/a>/i];for(const r of patterns){const m=block.match(r);if(m){const t=cleanText(m[1]);if(t&&t.length>=8&&!/Info\.tsx|css-|grid-template|Liczba pokoi/i.test(t))return t;}}return'';}
function extractOfferUrls(html){const urls=[];const seen=new Set();const add=(v,index)=>{const u=absoluteUrl(v,BASE);if(!u||!u.includes('/pl/oferta/'))return;if(seen.has(u))return;seen.add(u);urls.push({url:u,index});};for(const m of html.matchAll(/(?:href|url)=["'](https?:\/\/www\.otodom\.pl\/pl\/oferta\/[^"'#?]+|\/pl\/oferta\/[^"'#?]+)["']/gi))add(m[1],m.index||0);for(const m of html.matchAll(/(?:["']url["']\s*:\s*["'])(https?:\\?\/\\?\/www\.otodom\.pl\/pl\/oferta\/[^"']+)/gi))add(m[1],m.index||0);return urls.sort((a,b)=>a.index-b.index);}
function cardBlock(html,matches,i){const cur=matches[i],next=matches[i+1];const start=cur.index;const end=next?next.index:Math.min(html.length,start+16000);let block=html.slice(start,end);if(block.length<400){const s=Math.max(0,start-1200),e=Math.min(html.length,start+5000);block=html.slice(s,e);}return block;}
function parseOffers(html,sourceUrl,propertyType='mieszkanie'){const offers=[],seen=new Set(),matches=extractOfferUrls(html);const pt=String(propertyType||'mieszkanie').toLowerCase();const label=pt.includes('dom')?'Dom':(pt.includes('dział')||pt.includes('dzial'))?'Działka':(pt.includes('lokal')||pt.includes('komerc')||pt.includes('hale')||pt.includes('magaz'))?'Nieruchomość komercyjna':'Mieszkanie';for(let i=0;i<matches.length;i++){const{url}=matches[i];if(!url||seen.has(url))continue;const block=cardBlock(html,matches,i),text=cleanText(block),title=extractTitle(block),titleAreas=extractAreaCandidates(title),areas=titleAreas.length?titleAreas:extractAreaCandidates(text);if(!areas.length)continue;const area=areas[0].value,prices=extractPriceCandidates(text,area);if(!prices.length)continue;const areaIndex=areas[0].index;const price=prices.slice().sort((a,b)=>Math.abs(a.index-areaIndex)-Math.abs(b.index-areaIndex))[0].value;if(!Number.isFinite(price)||!Number.isFinite(area))continue;seen.add(url);offers.push({portal:PORTAL,type:label,locality:'',street:'',location:'',url,title,price,area,priceM2:price/area});}return offers;}
async function searchOtodom({location='Olsztyn',areaTarget=62,tolerance=10,radius=0,maxPages=20,propertyType='mieszkanie'}={}){const minArea=areaTarget*(1-tolerance/100),maxArea=areaTarget*(1+tolerance/100),pages=[],all=[];let totalHtmlLength=0,httpStatus=0,fetched=false,error='',recognized=0,emptyPages=0,previousSignature='';const requestedRadius=Number(radius)||0;const supportedRadius=[0,5,10,15,25,50,75].includes(requestedRadius)?requestedRadius:0;for(let page=1;page<=maxPages;page++){const url=buildUrl(location,minArea,maxArea,page,supportedRadius,propertyType);try{const r=await httpGet(url);httpStatus=r.status;totalHtmlLength+=r.body.length;fetched=fetched||r.status>=200&&r.status<400;const offers=parseOffers(r.body,url,propertyType);recognized+=offers.length;const filtered=offers.filter(o=>o.area>=minArea&&o.area<=maxArea&&Number.isFinite(o.price)&&o.url);all.push(...filtered);const signature=offers.map(o=>o.url).join('|');pages.push({page,url,httpStatus:r.status,htmlLength:r.body.length,recognized:offers.length,filtered:filtered.length});if(offers.length===0)emptyPages++;else emptyPages=0;if(page>1&&signature===previousSignature)break;previousSignature=signature;if(emptyPages>=1)break;}catch(e){error=String(e?.message||e);pages.push({page,url,httpStatus,htmlLength:0,recognized:0,filtered:0,error});break;}}const unique=[],seen=new Set();for(const o of all){const k=o.url.toLowerCase().replace(/\/$/,'');if(seen.has(k))continue;seen.add(k);unique.push(o);}return{portal:PORTAL,httpStatus,fetched,htmlLength:totalHtmlLength,recognized,complete:unique.length,filtered:unique.length,requestedRadius,appliedRadius:supportedRadius,radiusSupported:true,radiusStrategy:supportedRadius>0?'Otodom distanceRadius':'Otodom search without radius',pagesFetched:pages.length,portalAreaRange:{min:minArea,max:maxArea},pages,offers:unique,...(error?{error}:{})};}
module.exports={searchOtodom,buildUrl};